package com.touk.hiring_task.multiplex.commons

trait MultiplexException extends RuntimeException

trait ValidationException extends MultiplexException

case object InternalServerError extends MultiplexException
case object ProjectionNotFoundException extends MultiplexException
case object NoVacanciesForMovieException extends MultiplexException
case object SelectedPlaceUnavailableException extends MultiplexException
case object SelectedPlaceNotAvailableException extends MultiplexException

case object InvalidUsernameException extends ValidationException
case object InvalidStartProjectionDateException extends ValidationException
case object InvalidFinishProjectionDateException extends ValidationException
case object InvalidRangeOfDateException extends ValidationException
case object InvalidFullNameException extends ValidationException
case object InvalidRoomNameException extends ValidationException
case object InvalidMovieSelectedException extends ValidationException
case object InvalidPlaceCountException extends ValidationException
case object InvalidFirstNameLengthException extends ValidationException
case object InvalidFirstNameFormatException extends ValidationException
case object InvalidFamilyNameLengthException extends ValidationException
case object InvalidFamilyNameFormatException extends ValidationException
case object InvalidSecondFamilyNameLengthException extends ValidationException
case object InvalidSecondFamilyNameFormatException extends ValidationException
